// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cghhwdjmizfhpaqsmibi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnaGh3ZGptaXpmaHBhcXNtaWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4Mzc5MjcsImV4cCI6MjA1ODQxMzkyN30.fKBx8I9swYXeb4mkdVtTCpy-WJAnu5uw76W2tRYvLdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);